# This config follows a strategy described in the article
# Multi-objective Topic Modeling for Exploratory Search in Tech News
# by Anastasya Yanina, Lev Golitsyn and Konstantin Vorontsov, Jan 2018


# Use .format(modality=modality, dataset_path=dataset_path,
# specific_topics=specific_topics, background_topics=background_topics)
# when loading the recipe to adjust for your dataset

topics:
# Describes number of model topics, in the actuall article 200 topics were found to be optimal
    specific_topics: {specific_topics}
    background_topics: {background_topics}

regularizers:
- DecorrelatorPhiRegularizer:
    name: decorrelation_phi_{modality1}
    topic_names: specific_topics
    #tau_grid: [10**5, 10**6, 10**7, 10**8, 10**9, 10**10]
    class_ids: ['{modality1}']
- SmoothSparseThetaRegularizer:
    name: sparse_theta
    topic_names: specific_topics
    tau: 1
- SmoothSparsePhiRegularizer:
    name: smooth_phi_{modality1}
    topic_names: specific_topics
    #tau_grid: [0.25, 0.5, 0.75, 1.0, 1.25, 1.5]
    class_ids: ['{modality1}']
- DecorrelatorPhiRegularizer:
    name: decorrelation_phi_{modality2}
    topic_names: specific_topics
    #tau_grid: [10**5, 10**6, 10**7, 10**8, 10**9, 10**10]
    class_ids: ['{modality2}']
- SmoothSparseThetaRegularizer:
    name: sparse_theta
    topic_names: specific_topics
    tau: 1
- SmoothSparsePhiRegularizer:
    name: smooth_phi_{modality2}
    topic_names: specific_topics
    #tau_grid: [0.25, 0.5, 0.75, 1.0, 1.25, 1.5]
    tau: 1
    class_ids: ['{modality2}']

model: 
    dataset_path: {dataset_path}
    modalities_to_use: ['{modality1}', '{modality2}']
    main_modality: '{modality1}'

stages:
# repeat the following two cubes for every modality in the dataset
- RegularizersModifierCube:
    num_iter: 8
    selection:
        - PerplexityScore{modality1} < 1.1 * MINIMUM(PerplexityScore{modality1}) and SparsityPhiScore{modality2} -> max
    regularizer_parameters:
        - name: decorrelation_phi_{modality1}
          tau_grid: [10e5, 10e6, 10e7, 10e8, 10e9, 10e10]
        - name: decorrelation_phi_{modality2}
          tau_grid: [10e5, 10e6, 10e7, 1e8, 10e9, 10e10]
    tracked_score_function: PerplexityScore@all
    verbose: false
    use_relative_coefficients: false
- RegularizersModifierCube:
    num_iter: 8
    reg_search: add
    regularizer_parameters:
        name: sparse_theta
    selection:
        - PerplexityScore@all < 1.1 * MINIMUM(PerplexityScore@all) and SparsityPhiScore{modality1} -> max 
    strategy: PerplexityStrategy
    strategy_params:
        start_point: -0.5
        step: -0.5
        max_len: 6
    tracked_score_function: PerplexityScore@all
    verbose: false
    use_relative_coefficients: false
- RegularizersModifierCube:
    num_iter: 8
    reg_search: add
    regularizer_parameters:
        - name: smooth_phi_{modality1}
          tau_grid: [0.25, 0.5, 0.75, 1.0, 1.25, 1.5]
        - name: smooth_phi_{modality2}
          tau_grid: [0.25, 0.5, 0.75, 1.0, 1.25, 1.5]
    selection:
        - PerplexityScore{modality1} < 1.1 * MINIMUM(PerplexityScore{modality1}) and SparsityPhiScore{modality2} -> max
    tracked_score_function: PerplexityScore{modality1}
    verbose: false
    use_relative_coefficients: false
#last cube is independent of modalities and can be used only once